CREATE EXTENSION IF NOT EXISTS vector;
-- Таблица документов
CREATE TABLE news (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 	--уникальный ID базы
    dataset_id	TEXT,						--уникальное ID из датасета для связи с запросами
    article TEXT,						--исходный текст статьи
    fts_article TSVECTOR GENERATED ALWAYS AS (			--форма представления статьи для полнотекстового поиска
        to_tsvector('russian', COALESCE(article, ''))
    ) STORED,
    embedding vector(1024)					--векторизованное представление текста статьи 
);

-- GIN индекс для полнотекстового поиска
CREATE INDEX idx_news_fts ON news USING GIN(fts_article);

-- Запросы
CREATE TABLE query (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 	--унакальный ID базы
    dataset_id TEXT,						--уникальное ID из датасета для связи со статьями
    query_text TEXT NOT NULL,					--исходный текст запроса
    embedding vector(1024)					--вектризованное представление запроса
);

-- Эксперименты
CREATE TABLE run (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    description TEXT,						--описание запуска(параметры)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP		--метка времени
);

-- Результаты
CREATE TABLE result (
    query_id INTEGER REFERENCES query(id) ON DELETE CASCADE,	--какой запрос
    news_id INTEGER REFERENCES news(id) ON DELETE CASCADE,	--какой статье соответсвует 
    run_id INTEGER REFERENCES run(id) ON DELETE CASCADE,	--в рамках какого запуска
    rank INTEGER,						--с каким относительным ранком
    PRIMARY KEY (query_id, news_id, run_id)
);

-- Индексы для внешних ключей
CREATE INDEX idx_result_query ON result(query_id);
CREATE INDEX idx_result_news ON result(news_id);
CREATE INDEX idx_result_run ON result(run_id);

-- Индекс для быстрой сортировки 
CREATE INDEX idx_result_score_rank ON result(run_id, query_id, rank);

