CREATE EXTENSION IF NOT EXISTS vector;
-- Таблица документов
CREATE TABLE news (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dataset_id	TEXT,
    article TEXT,
    fts_article TSVECTOR GENERATED ALWAYS AS (
        to_tsvector('russian', COALESCE(article, ''))
    ) STORED
);

ALTER TABLE news ADD COLUMN embedding vector(1024);

-- GIN индекс для полнотекстового поиска
CREATE INDEX idx_news_fts ON news USING GIN(fts_article);

-- Запросы
CREATE TABLE query (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dataset_id TEXT,
    query_text TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE query ADD COLUMN embedding vector(1024);

-- Эксперименты
CREATE TABLE run (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Результаты
CREATE TABLE result (
    query_id INTEGER REFERENCES query(id) ON DELETE CASCADE,
    news_id INTEGER REFERENCES news(id) ON DELETE CASCADE,
    run_id INTEGER REFERENCES run(id) ON DELETE CASCADE,
    rank INTEGER,
    PRIMARY KEY (query_id, news_id, run_id)
);

-- Индексы для внешних ключей
CREATE INDEX idx_result_query ON result(query_id);
CREATE INDEX idx_result_news ON result(news_id);
CREATE INDEX idx_result_run ON result(run_id);

-- Индекс для быстрой сортировки по score
CREATE INDEX idx_result_score_rank ON result(run_id, query_id, score DESC, rank);
